### ISSUE TITLE
Question about this project

### ISSUE THREAD

**Issue by nai-kon** [sul-cidr/pianolatron#211]
Hello. 
I am personally creating a software called PlaySK Piano Roll Reader that converts piano roll images to midi in real time.
https://github.com/nai-kon/PlaySK-Piano-Roll-Reader

I'm excited about this great project!
The pianolatron's web-based UI is so beautiful and functional. 
Especially I was very surprised by the advanced features such as expression curves and note velocity overlays on roll images.
Now I want to know more about this Web App.

* Is it converting midi from roll images in real time? Or is it synchronizing the emulated midi to the scrolling image?
* Are there any plans to support Ampico rolls?

Thank you.

**Comment by broadwell** [comment]
Thanks for contacting us! The PlaySK Piano Roll Reader is extremely impressive, and we're excited to know that its development is ongoing.

The Pianolatron is meant to provide a web browser-based interactive player for a collection of reproducing and pianola rolls. It does not perform any real-time conversion from images to MIDI in the browser. This would be a very cool feature but probably would require a lot of changes to the code and might not work in many users' browsers.

Rather, the Pianolatron plays MIDI files that have been generated offline and synchronized to roll images via the code in [roll-image-parser](https://github.com/sul-cidr/roll-image-parser). It can use note velocities encoded in the MIDI via [midi2exp](https://github.com/sul-cidr/midi2exp) for Welte rolls. This feature also has been re-implemented in Javascript to allow for in-app changes to the expression emulation (available in the [develop](https://github.com/sul-cidr/pianolatron/tree/develop) branch).

The UI and infrastructure components of the Pianolatron are approaching stability, but further work will be needed to support other roll types as the digitized collection expands. The ability to play Duo-Art and Ampico rolls is at a very rudimentary stage. At first glance, it seems that we might learn much from the [PlaySK players](https://github.com/nai-kon/PlaySK-Piano-Roll-Reader/tree/master/src/players)!

**Comment by nai-kon** [comment]
Thank you for your detailed explanation.
The idea of ​​synchronizing pre-generated midi and roll images is amazing. This allows you to enjoy the piano roll visually, so I think it's much better than simply providing a midi file.

Among PlaySK's emulations, AmpicoB has received good reviews from user. On the other hand, Welte's emulation has tend to over loud, so it still needs adjustment. I would like to improve it by referring to the implementation of midi2exp.

**Comment by broadwell** [comment]
Yes, the roll images are hosted online in high resolution as part of the standard scanning and accessioning workflow, so it made sense to build a web-based player that could display them in synchronization with MIDI playback, because otherwise there isn't much value in just looking at the roll images (except for the few illustrated rolls).

Presumably the roll images from the collection could be downloaded and played in PlaySK with some minor changes to the code. It also would be very impressive if the input images could be streamed from the web via the IIIF image protocol to PlaySK, but that would be more difficult to implement.

FYI, the Welte emulation from midi2exp is also re-implemented in Javascript [here](https://github.com/sul-cidr/pianolatron/blob/develop/src/expression-boxes/lib/expression-welte-mignon.js); it may or may not be easier to relate this to PlaySK's code. This emulation was developed by Kitty Shi and Craig Sapp in consultation with Peter Phillips. They may also have struggled with the volume becoming too loud; I know that the rather arbitrary `left_adjust` parameter was added to attempt to prevent the bass from overwhelming the treble.

**Comment by nai-kon** [comment]
>the roll images from the collection could be downloaded and played in PlaySK

I'm very interested in it. I would like to try it out, but is the URL of the collection public?

Also, thank you for the re-implemented code. It's beautifully implemented and very easy to read.
It's not much different from my implementation, but I found out that there is an interesting parameter called welte_loud. I would like to take a closer look at the code.

**Comment by broadwell** [comment]
> I'm very interested in it. I would like to try it out, but is the URL of the collection public?

Yes, you can access the current contents of the collection here:
https://exhibits.stanford.edu/supra/browse/all-exhibit-items
The download links for the roll images are fairly difficult to find (we are working on an improved interface for this), but if you open a specific roll in the collection and then click the "Share & download" icon button at the top right of the image viewer, you'll see several download options, including the full original scan in JPEG2000 format, and a monochrome version of the full image in TIFF format.

**Comment by nai-kon** [comment]
Thank you so much.
I would like to try it right away !
